git subrepo clone --branch=c-api git@github.com:hoytak/turicreate.git turicreate_oss
subrepo:
  subdir:   "turicreate_oss"
  merged:   "4bcd182ac8"
upstream:
  origin:   "git@github.com:hoytak/turicreate.git"
  branch:   "c-api"
  commit:   "4bcd182ac8"
git-subrepo:
  version:  "0.3.1"
  origin:   "https://github.com/ingydotnet/git-subrepo"
  commit:   "a7ee886"

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,26 +18,26 @@ function print_help {
   echo "  --cleanup                         Clean up everything."
   echo
   echo "  --install-python-toolchain        Install python in local virtualenv."
-  echo  
+  echo
   echo "  --with-system-cmake (default)     Use system cmake, if avaliable."
   echo "  --no-system-cmake "
-  echo 
+  echo
   echo "  --with-ccache (default)           Use ccache, if available."
   echo "  --no-ccache "
-  echo  
+  echo
   echo "  --with-capi                       Build C API."
   echo "  --with-capi-framework             Build C API as OSX framework (OSX only)"
-  echo "  --no-capi (default)               " 
+  echo "  --no-capi (default)               "
 
   echo "  --with-python (default)           Build python components."
   echo "  --no-python"
-  echo 
+  echo
   echo "  --with-visualization (default)    Build Turi Create visualization client."
   echo "  --no-visualization"
   echo
   echo "  --python3                         Use Python 3.4, default is Python 2.7."
   echo "  --python3.5                       Use Python 3.5, default is Python 2.7."
-  echo 
+  echo
   echo "  --yes                             Defaults to yes on a prompt"
   echo
   echo "  -D var=value                      Specify CFLAGS definitions to be passed on to cmake."
@@ -81,8 +81,8 @@ function run_cleanup_prompt {
   fi
 }
 
-function install_python_toolchain { 
-  
+function install_python_toolchain {
+
   echo "Installing python toolchain."
   echo "python version = $PYTHON_VERSION."
 
@@ -116,18 +116,18 @@ python35=0
 while [ $# -gt 0 ]
   do case $1 in
     --cleanup)              cleanup_option=1;;
-    
+
     --install-python-toolchain) python_only=1;;
-    
+
     --with-system-cmake)    with_system_cmake=1;;
     --no-system-cmake)      with_system_cmake=0;;
 
     --with-ccache)          with_ccache=1;;
     --no-ccache)            with_ccache=0;;
-    
+
     --with-capi)            with_capi=1;;
     --with-capi-framework)  with_capi=1; with_capi_framework=1;;
-    --no-capi)              with_capi=0;; 
+    --no-capi)              with_capi=0;;
 
     --with-python)          with_python=1;;
     --no-python)            with_python=0;;
@@ -139,7 +139,7 @@ while [ $# -gt 0 ]
 
     --python3)              python3=1;;
     --python3.5)            python35=1;;
-    
+
     --help)                 print_help ;;
 
     -D)                     CMAKE_CONFIG_FLAGS="${CMAKE_CONFIG_FLAGS} -D $2"; shift ;;
@@ -173,12 +173,12 @@ fi
 
 if [[ $python_only == 1 ]]; then
   install_python_toolchain
-  exit $?  
+  exit $?
 fi
 
 # If we need to build python, we also need to install the python toolchain
 if [[ $with_python == 1 ]]; then
-  if [[ $with_visualization == 0 ]]; then 
+  if [[ $with_visualization == 0 ]]; then
     echo "Visualization client libraries (--with-visualization) required for python build."
     exit 1
   fi
@@ -232,7 +232,7 @@ fi
 # If not specified we assume gcc and g++ are the default c and c++
 # compilers
 if [[ -z $CC ]]; then
-  if [[ `which cc` ]]; then 
+  if [[ `which cc` ]]; then
     CC=cc
   elif [[ `which gcc` ]]; then
     CC=gcc
@@ -245,9 +245,9 @@ if [[ -z $CC ]]; then
 fi
 
 if [[ -z $CXX ]]; then
-  if [[ `which cxx` ]]; then 
+  if [[ `which cxx` ]]; then
     CXX=cxx
-  elif [[ `which c++` ]]; then 
+  elif [[ `which c++` ]]; then
     CXX=c++
   elif [[ `which g++` ]]; then
     CXX=g++
@@ -261,9 +261,9 @@ fi
 
 CCCMD=`which $CC || echo ""`
 CXXCMD=`which $CXX || echo ""`
-  
+
 echo "CC = $CCCMD"
-echo "CXX = $CXXCMD" 
+echo "CXX = $CXXCMD"
 
 echo "Attempting to use C compiler $CCCMD."
 echo "Attempting to use C++ compiler $CXXCMD."
@@ -277,7 +277,7 @@ mkdir -p $DEPS_PREFIX/bin
 rm -f $CCSCR
 rm -f $CXXSCR
 
-if [ $with_ccache -eq 1 ] && [ -f $CCACHE ]; then 
+if [ $with_ccache -eq 1 ] && [ -f $CCACHE ]; then
 
   echo "Using ccache from $CCACHE."
 
@@ -293,7 +293,7 @@ if [ $with_ccache -eq 1 ] && [ -f $CCACHE ]; then
   exit \$?
   " > $CXXSCR && chmod a+x $CXXSCR
 
-else 
+else
 
   echo "#!/bin/bash -e
   $CCCMD \$@
@@ -360,7 +360,7 @@ function install_cmake {
 
 CMAKE=`which cmake || echo ""`
 
-function check_cmake { 
+function check_cmake {
 
   if [[ -f $CMAKE ]] ; then
 
@@ -372,8 +372,8 @@ function check_cmake {
         install_cmake
         return $?
       fi
-    fi 
-    
+    fi
+
     if [[ -f ${PWD}/deps/local/bin/cmake ]]; then
       CMAKE=${PWD}/deps/local/bin/cmake
     fi
@@ -399,9 +399,9 @@ function check_cmake {
   fi
 }
 
-check_cmake || { 
-  echo "Error 1: Error reported installing CMake." 
-  exit 1 
+check_cmake || {
+  echo "Error 1: Error reported installing CMake."
+  exit 1
 }
 
 ########################################################
